import type { Metadata } from "next";
import { Urbanist, Ephesis } from "next/font/google";
import Header from "./components/layout/Header/Header";
import Footer from "./components/layout/Footer/Footer";
import "./scss/globals.scss";

// TODO: ?
const urbanist = Urbanist({
	variable: "--font-urbanist",
	subsets: ["latin"],
});

// TODO: ?
const ephesis = Ephesis({
	variable: "--font-ephesis",
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="cs">
			<body className={`${urbanist.variable} ${ephesis.variable}`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
